<?php
	# generated by EasyPack
	/** @var array $_lang */
	$_lang = array_merge(
		array (
  'setting_googleAmpModx_cache' => 'Включить кэширование',
  'setting_googleAmpModx_get' => 'Имя запроса',
  'setting_googleAmpModx_template' => 'Шаблон по умолчанию',
  'setting_googleAmpModx_warnings' => 'Вывести результат в Журнале ошибок',
)
		, $_lang);
	