<?php
	# generated by EasyPack
	/** @var array $_lang */
	$_lang = array_merge(
		array (
  'setting_googleAmpModx_cache' => 'Enable caching',
  'setting_googleAmpModx_get' => 'The name of the query',
  'setting_googleAmpModx_template' => 'Default Template',
  'setting_googleAmpModx_warnings' => 'Print the result in the Error Log',
)
		, $_lang);
	